// Used for canonical spelling and evidence in prose, not as a whitelist:
// unfamiliar skills explicitly listed in a skills section are retained too.
export const SKILL_ALIASES: Array<[string, string[]]> = [
  ['JavaScript', ['javascript', 'es6']],
  ['TypeScript', ['typescript']],
  ['React', ['react', 'react.js', 'reactjs']],
  ['Angular', ['angular']],
  ['Vue.js', ['vue', 'vue.js', 'vuejs']],
  ['Node.js', ['node.js', 'nodejs']],
  ['Python', ['python']],
  ['Java', ['java']],
  ['C#', ['c#', 'c sharp']],
  ['C++', ['c++']],
  ['Go', ['golang', 'go']],
  ['Rust', ['rust']],
  ['Ruby', ['ruby']],
  ['PHP', ['php']],
  ['Swift', ['swift']],
  ['Kotlin', ['kotlin']],
  ['SQL', ['sql']],
  ['PostgreSQL', ['postgresql', 'postgres']],
  ['MySQL', ['mysql']],
  ['Microsoft SQL Server', ['microsoft sql server', 'sql server', 'mssql']],
  ['MongoDB', ['mongodb']],
  ['Redis', ['redis']],
  ['Delphi', ['delphi']],
  ['AWS', ['aws', 'amazon web services']],
  ['Azure', ['azure', 'microsoft azure']],
  ['Google Cloud', ['google cloud', 'gcp']],
  ['Docker', ['docker']],
  ['Kubernetes', ['kubernetes']],
  ['Git', ['git']],
  ['REST APIs', ['rest api', 'rest apis', 'restful']],
  ['GraphQL', ['graphql']],
  ['HTML', ['html', 'html5']],
  ['CSS', ['css', 'css3']],
  ['Tailwind CSS', ['tailwind', 'tailwind css']],
  ['Next.js', ['next.js', 'nextjs']],
  ['Express', ['express.js', 'expressjs']],
  ['Django', ['django']],
  ['Django REST Framework', ['django rest framework', 'drf']],
  ['Flask', ['flask']],
  ['Spring Boot', ['spring boot']],
  ['TensorFlow', ['tensorflow']],
  ['PyTorch', ['pytorch']],
  ['Machine Learning', ['machine learning']],
  ['Data Analysis', ['data analysis', 'data analytics']],
  ['Power BI', ['power bi']],
  ['Tableau', ['tableau']],
  ['Excel', ['microsoft excel', 'excel']],
  ['Figma', ['figma']],
  ['Agile', ['agile']],
  ['Scrum', ['scrum']],
  ['Project Management', ['project management']],
  ['Communication', ['communication']],
  ['Leadership', ['leadership']],
  ['Customer Service', ['customer service']],
  ['Sales', ['sales']],
  ['Marketing', ['marketing']],
  ['Accounting', ['accounting']],
  ['Bookkeeping', ['bookkeeping']],
  ['Financial Analysis', ['financial analysis']],
  ['Graphic Design', ['graphic design']],
  ['UX Design', ['ux design', 'user experience design']],
  ['UI Design', ['ui design', 'user interface design']],
  ['Research', ['research']],
  ['Writing', ['writing']],
  ['Problem Solving', ['problem solving', 'problem-solving']],
  ['Teamwork', ['teamwork', 'team work']],
  ['Time Management', ['time management']],
  ['Microsoft Office', ['microsoft office', 'ms office']],
  ['SEO', ['seo', 'search engine optimization']],
  ['Solidity', ['solidity']],
  ['Smart Contracts', ['smart contracts', 'smart contract']],
  ['Blockchain Security', ['blockchain security']],
  ['Blockchain', ['blockchain']],
  ['Web3', ['web3', 'web 3']],
  ['Ethereum', ['ethereum']],
  ['Bitcoin', ['bitcoin']],
  ['EVM', ['evm', 'ethereum virtual machine']],
  ['DeFi', ['defi', 'decentralized finance']],
  ['DEX', ['dex', 'decentralized exchange']],
  ['DApps', ['dapps', 'dapp', 'decentralized applications']],
  ['ERC-20', ['erc-20', 'erc20', 'erc 20']],
  ['ERC-721', ['erc-721', 'erc721', 'erc 721']],
  ['ERC-1155', ['erc-1155', 'erc1155', 'erc 1155']],
  ['Smart Contract Architecture', ['smart contract architecture']],
  ['Smart Contract Security', ['smart contract security']],
  ['Hardhat', ['hardhat']],
  ['OpenZeppelin', ['openzeppelin', 'open zeppelin']],
  ['Tenderly', ['tenderly']],
  ['Etherscan', ['etherscan']],
  ['Blockchain Backend Integration', ['blockchain backend integration']],
  ['Technical Leadership', ['technical leadership']],
  ['Architecture', ['architecture']],
  ['Code Review', ['code review']],
  ['Team Guidance', ['team guidance']],
  ['Debugging', ['debugging']],
  ['Testing', ['testing']],
  ['Deployment', ['deployment']],
  ['CI/CD', ['ci/cd', 'continuous integration', 'continuous delivery']],
];

// These words can describe ordinary sentences rather than demonstrated skills.
export const AMBIGUOUS_PROSE_SKILLS = new Set([
  'Communication', 'Leadership', 'Customer Service', 'Sales', 'Marketing',
  'Accounting', 'Research', 'Writing', 'Teamwork', 'Architecture', 'Team Guidance',
  'Testing', 'Deployment', 'Go', 'Rust', 'Swift', 'Ruby', 'Excel',
]);
